resolver: lts-6.27
packages:
  - .
extra-deps:
# - etlas-1.6.0.0
- github: jneira/etlas
  commit: 7328c6d3c7f4e660e266fe1063f5afd1fabf0149
  subdirs:
  - etlas-cabal
- dhall-1.23
- ansi-terminal-0.7.1.1
- ansi-wl-pprint-0.6.8.2
- cryptonite-0.24
- formatting-6.3.2
- parsec-3.1.13.0
- megaparsec-7.0.4
- parser-combinators-1.0.0
- optparse-generic-1.3.0
- optparse-applicative-0.14.0.0
- Only-0.1
- memory-0.14.14
- basement-0.0.6
- prettyprinter-1.2.0.1
- prettyprinter-ansi-terminal-1.1.1.2
- directory-1.3.1.0
- foundation-0.0.19
- process-1.6.2.0
- repline-0.2.0.0
- haskeline-0.7.4.2
- aeson-1.2.3.0
- th-abstraction-0.2.6.0
- hashable-1.2.7.0
- Diff-0.3.4
- cborg-0.2.1.0
- serialise-0.2.1.0
- shell-escape-0.2.0
- cborg-json-0.2.1.0
- dotgen-0.4.2
- aeson-pretty-0.8.7
- tasty-hunit-0.10.0.1
