resolver: lts-6.27
packages:
  - .
extra-deps:
# - etlas-1.6.0.0
- github: jneira/etlas
  commit: 7328c6d3c7f4e660e266fe1063f5afd1fabf0149
  subdirs:
  - etlas-cabal
- dhall-1.26.1
# dhall
- ansi-terminal-0.7.1.1
- either-5
- ansi-wl-pprint-0.6.8.2
- cryptonite-0.24
- formatting-6.3.2
- megaparsec-7.0.4
- parser-combinators-1.0.0
- optparse-generic-1.3.0
- optparse-applicative-0.14.3.0
- Only-0.1
- memory-0.14.14
- basement-0.0.6
- prettyprinter-1.2.0.1
- prettyprinter-ansi-terminal-1.1.1.2
- directory-1.2.7.1
- foundation-0.0.19
- process-1.2.3.0
- repline-0.2.1.0
- haskeline-0.7.4.2
- aeson-1.2.3.0
- th-abstraction-0.2.6.0
- cborg-0.2.1.0
- serialise-0.2.1.0
- shell-escape-0.2.0
- cborg-json-0.2.1.0
- dotgen-0.4.2
- aeson-pretty-0.8.7
- transformers-compat-0.6.4
- exceptions-0.8.3
- mmorph-1.1.3
- monad-control-1.0.2.3
- cabal-doctest-1.0.6
- semigroupoids-5.3.2
- base-orphans-0.8.1
- profunctors-5.4
- tagged-0.8.6
- parsec-3.1.13.0
- text-1.2.3.1
- th-lift-instances-0.1.13
- th-lift-0.8.0.1
- data-fix-0.2.0
# golden-tests
- Diff-0.3.4
- tasty-hunit-0.10.0.1

flags:
  transformers-compat:
    four: true
