resolver: lts-6.27
packages:
  - .
extra-deps:
# - etlas-1.6.0.0
- github: typelead/etlas
  commit: 2380f80369fea16a24a27c2a95d21236f7fbce71
  subdirs:
  - etlas-cabal
# - dhall-1.17.0@rev:0
- github: dhall-lang/dhall-haskell
  commit: 110e1bf06e92d7dd21cadcb45b1d3fc8c2d79838
- ansi-terminal-0.7.1.1
- ansi-wl-pprint-0.6.8.2
- cryptonite-0.24
- formatting-6.3.2
- parsec-3.1.13.0
- megaparsec-7.0.0
- parser-combinators-1.0.0
- optparse-generic-1.3.0
- optparse-applicative-0.14.0.0
- Only-0.1
- memory-0.14.14
- basement-0.0.6
- prettyprinter-1.2.0.1
- prettyprinter-ansi-terminal-1.1.1.2
- directory-1.3.1.0
- foundation-0.0.19
- process-1.6.2.0
- repline-0.1.7.0
- haskeline-0.7.4.2
- insert-ordered-containers-0.2.1.0
- aeson-1.2.3.0
- th-abstraction-0.2.6.0
- hashable-1.2.7.0
- Diff-0.3.4
# Version 0.2.0.0 of cborg, the latest on Hackage, is broken on i386.
- github: well-typed/cborg
  commit: master
  subdirs:
    - cborg
    - serialise
- tasty-hunit-0.10.0.1
